version: '3'

services:
  app:
    image: app:latest
    ports:
      - 8080:8080
      #- 8080:8081
    command: "java -jar --Dspring.profiles.active=prd tellus-springboot-0.0.1-SNAPSHOT.jar"
    #command: "java -jar --Dspring.profiles.active=hml tellus-springboot-0.0.1-SNAPSHOT.jar"