version: '3'

services:
  app:
    image: backend:latest
    ports:
      - 8082:81
      #- 8080:8080
    command: "java -jar -Dserver.port=8082 tellus-springboot-0.0.1-SNAPSHOT.jar"
    #command: "java -jar -Dserver.port=8080 tellus-springboot-0.0.1-SNAPSHOT.jar"