FROM openjdk:11-jdk

USER root

RUN mkdir -p /usr/src/backend
WORKDIR /usr/src/backend

COPY target/*.jar /usr/src/backend

CMD ["java","--Dspring.profiles.active=prd", "-Dmaven.test.skip=true" ,"--jar","tellus-springboot-0.0.1-SNAPSHOT.jar"]
